spring:
  application:
    name: NewsMind
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}     # ????
      chat:
        options:
          model: gpt-4o-mini
app:
  ai:
    enabled: true         # ??? false? ?? ??
  search:
    provider: newsapi     # ??? ??? ?? ???
    newsapi:
      api-key: ${NEWS_API_KEY}
      page-size: 10
    translate:
      provider: azure
azure:
  translator:
    key: ${AZURE_TRANSLATOR_KEY}
    endpoint: https://api.cognitive.microsofttranslator.com
    region: eastasia   # ??? ??

logging:
  level:
    org.hibernate.SQL: debug