spring:
  application:
    name: NewsMind
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
  sql:
    init:
      mode: always
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    thymeleaf:
      cache: false
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
# MyBatis 설정
mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.newsapp.newsmind.domain
  configuration:
    map-underscore-to-camel-case: true
app:
  ai:
    enabled: true
  newsdata:
    api-key: ${NEWSDATA_API_KEY}
    base-url: https://newsdata.io/api/1
azure:
  translator:
    key: ${AZURE_TRANSLATOR_KEY}
    endpoint: https://api.cognitive.microsofttranslator.com
    region: eastasia
kakao:
  client-id: ${KAKAO_LOGIN_REST_API_KEY}
  redirect-uri: ${KAKAO_LOGIN_REDIRECT_URI}
logging:
  level:
    org.hibernate.SQL: debug
jwt:
  secret-key: "A7F6C1C492D4A9B7E3F1D6C9A4F8E2B1"
  access-expire-ms: 3600000        # 1시간
  refresh-expire-ms: 1209600000    # 14일